version: '3.8'

services:
  web:
    image: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/mi_basedatos
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_basedatos
    ports:
      - "3308:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
