version: '3'
services:
  flask_app:
    image: flask_app_image  # Reemplaza esto con tu propia imagen de Flask, o puedes definir un build en caso de que quieras construir la imagen
    build:
      context: .
      dockerfile: Dockerfile  # Especifica tu Dockerfile si lo necesitas
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql  # El nombre del servicio MySQL que definimos en GitHub Actions
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mi_basedatos
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql  # Asegura que MySQL esté levantado antes de iniciar Flask
    networks:
      - app_network  # Conectamos flask_app a la red app_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_basedatos
    ports:
      - "3309:3306"
    networks:
      - app_network  # Conectamos mysql a la red app_network

networks:
  app_network:  # Definimos la red 'app_network'
    driver: bridge
