version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ejemplo2_sqlserver_1
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433"  # Puerto dinámico, Docker asignará un puerto aleatorio
    networks:
      - app_network
    volumes:
      - sqlserver_data:/var/opt/mssql

  flask:
    build:
      context: ./flask  # La carpeta donde está el Dockerfile de Flask
    container_name: ejemplo2_flask_1
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=mssql+pyodbc://sa:YourStrong!Passw0rd@sqlserver:1433/your_database?driver=ODBC+Driver+17+for+SQL+Server
    ports:
      - "5000:5000"  # Puerto de Flask
    depends_on:
      - sqlserver
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
