version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always  # Reinicia el servicio si falla
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    healthcheck:  # Chequeo de salud para saber si está listo
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask:
    build:
      context: ./flask
    container_name: flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy  # Espera a que MySQL esté sano antes de iniciar Flask
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: testdb
