name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Instalar Docker y Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        sudo systemctl start docker

    - name: Construir y levantar los contenedores
      run: |
        docker-compose up -d --build

    - name: Verificar los contenedores activos
      run: docker ps

    # Esto es opcional para mantener el runner activo si necesitas pruebas
    - name: Mantener el contenedor activo por 1 hora (opcional)
      run: sleep 3600
