name: CI/CD para App Flask y MySQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mi_basedatos
        ports:
          - 3306:3306

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Instalar Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Crear y ejecutar los contenedores
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Verificar si la aplicación está corriendo
      run: |
        sleep 10  # Espera a que los servicios estén listos
        curl http://localhost:5000  # Reemplaza con la URL correcta de tu app

    - name: Detener los contenedores
      run: |
        docker-compose down
