name: Proyecto con pruebas de sistema

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  despliegue:
    name: Desplegar servicios en pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4  # Actualizado a v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3  # Actualizado a v3

      - name: Limpiar contenedores antiguos
        run: docker compose down --volumes --remove-orphans || true

      - name: Levantar los servicios de Flask y MySQL
        run: |
          docker compose up -d --build
          echo "Esperando que los servicios arranquen..."
          sleep 20

      - name: Mostrar logs de Flask
        run: docker logs flask > flask_logs.txt  # Guardamos los logs en un archivo

      - name: Subir logs como artefacto
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: logs-flask
          path: flask_logs.txt  # El archivo generado de los logs

  pruebas:
    name: Ejecutar pruebas de sistema
    runs-on: ubuntu-latest
    needs: despliegue

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4  # Actualizado a v4

      - name: Instalar dependencias de pruebas
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt  # Instalamos las dependencias de pruebas

      - name: Mostrar contenedores en ejecución
        run: docker ps -a

      - name: Verificar respuesta simple de Flask desde el contenedor
        run: |
          echo "Verificando respuesta simple de Flask desde el contenedor..."
          docker exec flask curl --retry 5 --retry-delay 5 http://localhost:5000 || echo "Fallo al conectar, revisa los logs."

      - name: Ejecutar pruebas automáticas y generar reporte HTML
        run: |
          pytest tests/test_app.py --html=tests/report/report.html --self-contained-html  # Generamos un reporte HTML independiente

      - name: Subir reporte de pruebas
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: reporte-pruebas
          path: tests/report/report.html  # Subimos el reporte HTML generado