name: Proyecto

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Clean up previous containers (if any)
        run: |
          docker compose down --volumes --remove-orphans || true

      - name: Build and run containers
        run: |
          docker compose up -d
          echo "Esperando 15 segundos para que los servicios se inicialicen..."
          sleep 15

      - name: Mostrar logs de SQL Server
        run: docker logs sqlserver

      - name: Mostrar logs de Flask
        run: docker logs flask

      # Aquí podrías poner tus pruebas o verificaciones de conexión
      - name: Verificar conexión SQL Server
        run: |
          echo "Verificando si SQL Server está corriendo..."
          docker exec sqlserver /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT @@VERSION'

      - name: Tear down containers
        if: always()  # Esto asegura que se ejecute aunque falle un paso anterior
        run: docker-compose down --volumes --remove-orphans
