name: Proyecto con pruebas de sistema

on:
  push:
    branches:
      - main

jobs:
  despliegue:
    name: Desplegar servicios en pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Limpiar contenedores antiguos
        run: docker compose down --volumes --remove-orphans || true

      - name: Levantar los servicios de Flask y MySQL
        run: |
          docker compose up -d --build
          echo "Esperando que los servicios arranquen..."
          sleep 20

      - name: Mostrar logs de Flask
        run: docker logs flask

  pruebas:
    name: Ejecutar pruebas de sistema
    runs-on: ubuntu-latest
    needs: despliegue

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias de pruebas
        run: pip install -r requirements-test.txt

      - name: Mostrar contenedores en ejecución
        run: docker ps -a
      
      - name: Verificar respuesta simple de Flask desde el contenedor
        run: |
          echo "Verificando respuesta simple de Flask desde el contenedor..."
          docker exec flask curl --retry 5 --retry-delay 5 http://localhost:5000
      
      - name: Ejecutar pruebas automáticas
        run: pytest tests/

      - name: Apagar y limpiar servicios
        if: always()
        run: docker compose down --volumes --remove-orphans
