name: Proyecto

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Clean up previous containers (if any)
        run: |
          docker compose down --volumes --remove-orphans || true

      - name: Build and run containers
        run: |
          docker compose up -d --build
          echo "Esperando 15 segundos para que los servicios se inicialicen..."
          sleep 15

      - name: Mostrar logs de Flask
        run: docker logs flask

      - name: Verificar respuesta del servicio Flask
        run: |
          echo "Verificando respuesta del servicio Flask..."
          curl --retry 5 --retry-delay 5 http://localhost:5000

      - name: Tear down containers
        if: always()  # Esto asegura que se ejecute aunque falle un paso anterior
        run: docker compose down --volumes --remove-orphans
