name: Proyecto

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a la rama "main"

jobs:
  construir:
    runs-on: ubuntu-latest  # Utiliza un runner de Ubuntu

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2  # Clona el código del repositorio en el runner

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configura Buildx para construir imágenes Docker

      - name: Limpiar contenedores anteriores 
        run: |
          docker compose down --volumes --remove-orphans || true
        # Detiene y elimina contenedores, volúmenes y redes antiguas

      - name: Construir y levantar los contenedores
        run: |
          docker compose up -d --build
          echo "Esperando 15 segundos para que los servicios se inicialicen..."
          sleep 15
        # Levanta los servicios en segundo plano y espera para asegurar que estén listos

      - name: Mostrar los logs del servicio Flask
        run: docker logs flask
        # Muestra los logs del contenedor de Flask para revisar su estado

      - name: Verificar la respuesta del servicio Flask
        run: |
          echo "Verificando la respuesta del servicio Flask..."
          curl --retry 5 --retry-delay 5 http://localhost:5000
        # Realiza una solicitud HTTP al endpoint de Flask y reintenta en caso de fallo

      - name: Apagar y limpiar los contenedores
        if: always()  # Se ejecuta siempre, aunque haya fallado algún paso anterior
        run: docker compose down --volumes --remove-orphans
        # Detiene y elimina contenedores, volúmenes y redes después de las pruebas
